### ISSUE TITLE
which version of geokit?

### ISSUE THREAD

**Issue by johntoups** [cesarediaz/inventory#1]
running geokit 1.5.0 and inventory asserts:

```
inventory/config/initializers/geokit_config.rb:10: undefined method `timeout=' for Geokit::Geocoders:Module (NoMethodError)
from inventory/vendor/rails/activesupport/lib/active_support/dependencies.rb:142:in `load_without_new_constant_marking'
from inventory/vendor/rails/activesupport/lib/active_support/dependencies.rb:142:in `load'
from inventory/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in `new_constants_in'
from inventory/vendor/rails/activesupport/lib/active_support/dependencies.rb:142:in `load'
```

**Comment by johntoups** [comment]
Sorry, found it on wiki - 1.3.0

**Comment by johntoups** [comment]
closing...
